### ISSUE TITLE
Configure consul repo

### ISSUE THREAD

**Issue by bertocq** [consul/installer#1]
Right now this installer clones consul/consul repo but its recommended to use a fork in order to be able to make customizations and store them in version control.

So I guess we could add steps to:
1. Create a consul fork (if it doesn't exist already)
https://consul_docs.gitbooks.io/docs/content/en/forks/create.html
2. Configure the fork's url at https://github.com/consul/installer/blob/configuration/roles/rails/tasks/main.yml#L10 and

For the second step, it would be nice to avoid changing the installer source code. I guess passing the git repo url as a parameter of the `sudo ansible-playbook -v consul.yml -i hosts --extra-vars "target=vagrant"` could work? But the best solution would be to store a particular installation details on a file.. maybe consul.yml? I don't know 🙈

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/installer/pull/49
