### ISSUE TITLE
Unicorn can no longer be exetuted as deploy user

### ISSUE THREAD

**Issue by rcala6900** [consul/installer#100]
Hello,
today I deployed Consul on a new server. The installation worked straightforward, except that in my previous attempt. about a month ago, I was able to schedule unicorn to start at boot using user "deploy", in this new instance it can only be run as root.

If I "sudo chown -R deploy:wheel /home/deploy/consul" then I'm able to start it againg with user "deploy".

What's best?

Thank you for your help
Best regards

**Comment by voodoorai2000** [comment]
Hey @rcala6900!

Happy you found a workaround 🎉

Sorry about that, we [introduced a simplification](https://github.com/consul/installer/commit/f406a2f1ceb330f065360c20ece9008ebaf9c9e4) that can change the permissions of some folders. 🙏

Working on reverting that change.

For now... yes using `chown` is fine, here is [another workaround]
(https://github.com/consul/consul/commit/0c6f31f27a175cc81cfd653838ab07da60e89909). 🙏
