### ISSUE TITLE
Installer - Spec Fail

### ISSUE THREAD

**Issue by ziyan-junaideen** [consul/installer#107]
I was having a deploy running v0.19. Then I rebased it on top of v1.0.0 and did a Capistrano deployment. Then I noticed some thing like (or at least that is what I have now).

```
01:36 deploy:restart
      01 /etc/init.d/unicorn_consul restart
      01 bash: /etc/init.d/unicorn_consul: No such file or directory
      01
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@157.230.14.200: /etc/init.d/unicorn_consul restart exit status: 127
/etc/init.d/unicorn_consul restart stdout: bash: /etc/init.d/unicorn_consul: No such file or directory
```

Then I thought of running the installer as some thing seemed to be missing. After some fixes the installation got stuck in specs. Then I thought of running it on a bare Ubuntu 16.04 server with a not modified (except the base config) and ended up in the same error.

I didn't see any thing related to the error in the issue list so thought of opening an issue.

BTW is there upgrade docs that give advice on upgrading. I remember getting an email from v0.18 to v0.19. But couldn't find a page that might suggest some thing like.

```

TASK [specs : Redirect to https] ****************************************************************************************************************
skipping: [192.241.137.219] => changed=false 
  skip_reason: Conditional result was False

TASK [specs : uri] ******************************************************************************************************************************
fatal: [192.241.137.219]: FAILED! => changed=false 
  connection: close
  content: |-
    <html>
    <head><title>502 Bad Gateway</title></head>
    <body bgcolor="white">
    <center><h1>502 Bad Gateway</h1></center>
    <hr><center>nginx/1.10.3 (Ubuntu)</center>
    </body>
    </html>
  content_length: '182'
  content_type: text/html
  date: Fri, 19 Jul 2019 13:27:32 GMT
  elapsed: 0
  msg: 'Status code was 502 and not [200]: HTTP Error 502: Bad Gateway'
  redirected: false
  server: nginx/1.10.3 (Ubuntu)
  status: 502
  url: http://127.0.0.1

PLAY RECAP **************************************************************************************************************************************
192.241.137.219            : ok=77   changed=54   unreachable=0    failed=1    skipped=29   rescued=0    ignored=0 
```

**Comment by microweb10** [comment]
Hi @ziyan-junaideen 😄 
For what I see in the errors it seems that the code in the branch `capistrano` is missing.
In the documentation https://github.com/consul/installer#deploys-with-capistrano there's a part when you have to merge the branch capistrano into your local branch
```
git remote add upstream git@github.com:consul/consul.git
git fetch upstream
git merge upstream/capistrano
```
Could you try that? And then and execute `cap production deploy` again to see if it works? ☺️

**Comment by voodoorai2000** [comment]
Hey @ziyan-junaideen,

Right sorry about that one, I think it has to do with the order in which commands are executed.

As shown in the [screencast](https://github.com/consul/installer#screencast-1), after running the capistrano role in the Installer, we still need to run a `cap production deploy` from a local machine to complete the capistrano setup.

I believe what you are seeing is a false negative, we'll fix it 🙏
Everything looks good in your setup, try running that `cap production deploy` from your local machine. 

And yes please take into account @microweb10's comment too, that's another common gotcha.

**Comment by javierm** [comment]
@ziyan-junaideen Did microweb's and Rai's comments help you with this issue?

I'm closing this issue because we now use puma instead of unicorn, but if you need more help with this issue, just ask :wink:.
