### ISSUE TITLE
Configuring Paperclip or ActiveStorage

### ISSUE THREAD

**Issue by LucasCioffi** [consul/installer#108]
Hello, at [this page](https://docs.consulproject.org/docs/spanish-documentation/introduction/servers/deploying-on-heroku?q=paperclip) the search results for Paperclip installation are not working.
<img width="1438" alt="Screen Shot 2019-07-26 at 6 30 29 PM" src="https://user-images.githubusercontent.com/1825103/61984748-97b9b080-afd3-11e9-8e2e-5222c3c84bf3.png">

Maybe those search results are cached and should be deleted?

Where can I find the current instructions for configuring Paperclip or ActiveStorage?  Thank you!

**Comment by LucasCioffi** [comment]
These [Paperclip instructions on Heroku](https://devcenter.heroku.com/articles/paperclip-s3) worked for me.

**Comment by PierreMesure** [comment]
Hey Lucas, you can find the instructions [here](https://github.com/consul/docs/blob/master/en/installation/deploying-on-heroku.md). I'm not sure why they don't show up in the guide.

**Comment by javierm** [comment]
@LucasCioffi Thanks for reporting! Seems to be an issue with the docs :thinking:. Closing in favor of consul/docs#114.
