### ISSUE TITLE
Make the playbook inmutable

### ISSUE THREAD

**Issue by voodoorai2000** [consul/installer#12]
What
===
If the script is only run once and everything goes smoothly there is no problem...
However if something goes wrong, some roles are not prepared to be run a second time

We should make the playbook inmutable, thus being able to run the playbook multiple times without seeing errors due t changes in the state of the server

Checkout:
- [ ] [Capistrano](https://github.com/consul/installer/blob/master/roles/capistrano/tasks/main.yml) role

**Comment by zenny** [comment]
+1

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/installer/pull/17
