### ISSUE TITLE
Syntax error on the TASK: [rails : Create Database]

### ISSUE THREAD

**Issue by mauroprosperi** [consul/installer#132]
SyntaxError: /home/deploy/consul/releases/0-installer/config/environments/production.rb:80: syntax error, unexpected keyword_end, expecting '}'

fatal: [10.3.0.27]: FAILED! => changed=true 
  cmd: source /home/deploy/.rvm/scripts/rvm && bin/rake db:migrate RAILS_ENV=production
  delta: '0:00:03.969313'
  end: '2019-11-14 15:56:58.031878'
  msg: non-zero return code
  rc: 1
  start: '2019-11-14 15:56:54.062565'
  stderr: |-
    rake aborted!
    SyntaxError: /home/deploy/consul/releases/0-installer/config/environments/production.rb:80: syntax error, unexpected keyword_end, expecting '}'
      end
         ^
    /home/deploy/consul/releases/0-installer/config/environments/production.rb:105: syntax error, unexpected ':', expecting keyword_end
        address:              "smtp.example.co
                ^
    /home/deploy/consul/releases/0-installer/config/environments/production.rb:105: syntax error, unexpected ',', expecting end-of-input
               "smtp.example.com",
                                  ^
    /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
    /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `block in require'
    /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
    /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
    /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/railties-5.0.7.2/lib/rails/engine.rb:600:in `block (2 levels) in <class:Engine>'
    /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/railties-5.0.7.2/lib/rails/engine.rb:599:in `each'
    /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/railties-5.0.7.2/lib/rails/engine.rb:599:in `block in <class:Engine>'
    /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/railties-5.0.7.2/lib/rails/initializable.rb:30:in `instance_exec'
    /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/railties-5.0.7.2/lib/rails/initializable.rb:30:in `run'
    /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/railties-5.0.7.2/lib/rails/initializable.rb:55:in `block in run_initializers'
    /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/railties-5.0.7.2/lib/rails/initializable.rb:44:in `each'
    /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/railties-5.0.7.2/lib/rails/initializable.rb:44:in `tsort_each_child'
    /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/railties-5.0.7.2/lib/rails/initializable.rb:54:in `run_initializers'
    /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/railties-5.0.7.2/lib/rails/application.rb:352:in `initialize!'
    /home/deploy/consul/releases/0-installer/config/environment.rb:5:in `<top (required)>'
    /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
    /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `block in require'
    /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
    /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
    /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/railties-5.0.7.2/lib/rails/application.rb:328:in `require_environment!'
    /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/railties-5.0.7.2/lib/rails/application.rb:448:in `block in run_tasks_blocks'
    Tasks: TOP => db:migrate => environment
    (See full trace by running task with --trace)
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

**Comment by javierm** [comment]
Hi @mauroprosperi. Given the error:

```
SyntaxError: /home/deploy/consul/releases/0-installer/config/environments/production.rb:80: syntax error, unexpected keyword_end, expecting '}'
```

It looks like there's a syntax error on your `config/environments/production.rb` file :thinking:. Have you changed this file manually? You can compare it against [CONSUL's production environment file](https://github.com/consul/consul/blob/master/config/environments/production.rb) and maybe the differences will show where the syntax error is.

**Comment by mauroprosperi** [comment]
I check and they are different! I never touch the files manually until now... I'm gonna try to download it again, thanks.
