### ISSUE TITLE
rake aborted - cannot load github_changelog_generator/task

### ISSUE THREAD

**Issue by bloomingmath** [consul/installer#136]
I'm following the readme to deploy consul on a digitalocean droplet. Got stuck with this task 

> TASK [rails : Generate secret key] *******************************************************
> fatal: [167.99.174.84]: FAILED! => changed=true 
>   cmd: source /home/deploy/.rvm/scripts/rvm && bin/rake secret
>   delta: '0:00:03.601932'
>   end: '2019-11-24 17:24:46.745948'
>   msg: non-zero return code
>   rc: 1
>   start: '2019-11-24 17:24:43.144016'
>   stderr: |-
>     rake aborted!
>     LoadError: cannot load such file -- github_changelog_generator/task
>     /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
>     /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `block in require'
>     /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
>     /home/deploy/consul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
>     /home/deploy/consul/releases/20191124151823/Rakefile:10:in `<top (required)>'
>     (See full trace by running task with --trace)
>   stderr_lines: <omitted>
>   stdout: ''
>   stdout_lines: <omitted>

Running the same command from the remote server gives the same error.

**Comment by bloomingmath** [comment]
I'm not even sure it is the right kind of problem to post as an issue...

**Comment by microweb10** [comment]
Hi @bloomingmath!

Thank you very much for posting the issue! This is the right place to do it ☺️ 

We have just merged a PR that should fix the problem.

Could you please update your repository `git pull origin master` and try to run the installer `ansible-playbook -v consul.yml -i hosts` again? 🙏 

It should work fine this time 😄 

Apologies for the inconvenience!

**Comment by bloomingmath** [comment]
Thanks, looks good to me!
