### ISSUE TITLE
A group 'wheel' is not default on Ubuntu and should not be used

### ISSUE THREAD

**Issue by bliekp** [consul/installer#141]
Why depend on a group 'wheel' when it's not default?

Better to document the process better and add the user deploy to the sudoers file with visudo. This is a generic solution that should work on all (or most) Linux distro's.

**Comment by bkmgit** [comment]
This is a helpful suggestion, as indicated at https://askubuntu.com/questions/1036167/unable-to-create-user-on-ubuntu-server-with-ansible `wheel` is available in Debian, but not in Ubuntu where the equivalent group is `sudo`. On Ubuntu, one can change https://github.com/consul/installer/blob/1.4.1/group_vars/all#L14 from
```
deploy_group: wheel
```
to
```
deploy_group: sudo
```
