### ISSUE TITLE
Dont change anything with deploy ansible with my git

### ISSUE THREAD

**Issue by Jdemurga** [consul/installer#143]
When I run "sudo ansible-playbook -v consul.yml -i hosts", the process is done correctly, but none of my changes are visible. I follow all steps for this again, but didnt works.
I have modified the path of the git repository but it seems that it does not affect anything, because there are no files that I have created.

**Comment by javierm** [comment]
Hi, @Jdemurga. If I understand correctly, you've already installed CONSUL, and you're trying to change the code and upload these changes.

If that's the case, you need to [deploy with Capistrano](https://github.com/consul/installer#deploys-with-capistrano).

Hope that helps!

**Comment by javierm** [comment]
@Jdemurga I'm closing this issue since it seems to me the answer is already in the documentation. Feel free to reopen it if I'm wrong :wink:.
