### ISSUE TITLE
502 Bad Gateway After Restart Ubuntu Server

### ISSUE THREAD

**Issue by ernestogarj** [consul/installer#144]
Hello I use the installer to install consul on Ubuntu 16.04 It´s works ok and I can acceso to consul but when I restart the server It show 502 error Bad Gateway, Nginx it´s running and PostgresSql, How could I to fix it?

Thanks

**Comment by javierm** [comment]
Hi, @ernestogarj.

Which version of the installer are you using? We had this bug in version 1.0.0 (see issue #94), but it should be fixed in the master branch :thinking:.

**Comment by ernestogarj** [comment]
> Hi, @ernestogarj.
> 
> Which version of the installer are you using? We had this bug in version 1.0.0 (see issue #94), but it should be fixed in the master branch 🤔.

I think it is the last version i follow the tutorial on consul/installer and clone the repository
