### ISSUE TITLE
Placeholder for user name in cron/whenever setup

### ISSUE THREAD

**Issue by smarques** [consul/installer#152]
Hi, I am wondering if this line should use a placeholder for the cron user to use

https://github.com/consul/installer/blob/48f7984ceceec55cc05627d8c7d0a8ac41332fcc/roles/rails/tasks/main.yml#L75

or am I missing something?
I had expected this to use the deploy user, while I see "consul" hardcoded.

Thank you

**Comment by javierm** [comment]
@smarques Thanks for reporting! :pray: The gem `whenever` automatically generates the cron for the user who is executing the command. So here, `consul` is not the username but the application's name.

Having said that, you've got a great point here :smile:, and that name shouldn't be hardcoded. I've openen pull request #153 to fix it. Hope that's OK!
