### ISSUE TITLE
Ubuntu 20.04 Support?

### ISSUE THREAD

**Issue by corsch** [consul/installer#154]
I've tried to run the installer on Ubuntu 20.04 and have the following error

TASK [system : Add Node repository] *********************************************************************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => changed=false
  msg: apt cache update failed

Is Ubuntu 20.04 not yet supported?

**Comment by javierm** [comment]
Hi, @corsch :smile:.

I'm afraid Ubuntu 20.04 is not supported yet; only 16.04 and 18.04 are supported so far.
