### ISSUE TITLE
Error running rails console

### ISSUE THREAD

**Issue by pmarkun** [consul/installer#158]
Hi there,

I've followed the instructions but when I run: 

cd /home/deploy/consul/ && bin/rails c production to search for errors in the smtp sending I got:

bash: bin/rails: No such file or directory

Tried changing it to:

cd /home/deploy/consul/ && current/bin/rails

But then I got:

Traceback (most recent call last):
	4: from current/bin/rails:3:in `<main>'
	3: from current/bin/rails:3:in `require_relative'
	2: from /home/deploy/consul/releases/20200930000648/config/boot.rb:3:in `<top (required)>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler/setup (LoadError)

Any hints?

**Comment by javierm** [comment]
@pmarkun Thank you very much for reporting! :pray:

I've opened pull request #159 with a fix. Can you confirm the [updated instructions](https://github.com/consul/installer/blob/977df016ac813e5418442ba9abd795824c4b89b6/README.md#screencast-2) work for you?
