### ISSUE TITLE
Support other GNU/Linux distributions

### ISSUE THREAD

**Issue by voodoorai2000** [consul/installer#16]
It would be great if we could make the installer fully compatible with other distributions, like Debian, instead of supporting just Ubuntu.

Note: in order to support other distributions we'd have to find a way to run the tests on machines with those distributions.

**Comment by javierm** [comment]
Since CentOS (the system which this issue was originally created for) is no longer being developed and it offers very basic support for old versions (support for CentOS 8 will end next week and CentOS 7 is now seven years old), this issue will be closed when we add support for Debian.
