### ISSUE TITLE
Install Error SSH Key

### ISSUE THREAD

**Issue by TLHN** [consul/installer#161]
Hi there,

i am running ubuntu 18.04.5 with the recommended prerequsites

`TASK [user : Install SSH key] ***********************************************************************************************************************************************************************************************************************************************************************************************
task path: /root/installer/roles/user/tasks/main.yml:21
[WARNING]: Unable to find '~/.ssh/id_rsa.pub' in expected paths (use -vvvvv to see paths)
File lookup using None as file
fatal: [127.0.0.1]: FAILED! =>
  msg: 'An unhandled exception occurred while running the lookup plugin ''file''. Error was a <class ''ansible.errors.AnsibleError''>, original message: could not locate file in lookup: ~/.ssh/id_rsa.pub'

PLAY RECAP ******************************************************************************************************************************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
`

i keep getting this error with the ssh key.

what do i have to do here?

my hosts is simply

127.0.0.1

this is what i use for install 

 ansible-playbook -v consul.yml -i hosts --user root --ask-pass -vvvv

**Comment by javierm** [comment]
Hi, @TLHN.

The installer will authorize your public SSH key so you can access the remote machine in the future without a password. If you already have a SSH key in a different path, change `ssh_public_key_path` to the right path in `group_vars/all`. If you don't have a SSH key, you can generate one using [ssh-keygen](https://www.ssh.com/ssh/keygen/).

Hope that helps!

**Comment by javierm** [comment]
@TLHN I'm assuming that was the issue and, since we've already got an open issue (#39) related to documenting SSH keys generation, I'm closing this one as a duplicate. Feel free to reopen if that's not the case :wink:.
