### ISSUE TITLE
Error al modificar estilos y subir imagenes

### ISSUE THREAD

**Issue by profesionalTI** [consul/installer#162]
Estimados,

Junto con Saludarlos, tengo un problema técnico, resulta que he estado editando los estilos y subiendo imágenes en:

/home/deploy/consul/current/app/assets/images
/home/deploy/consul/current/app/assets/stylesheets/custom.scss

Creo que con reiniciar el servidor en Ubuntu no basta, necesito hacer algo más para que se actualice la cache de la app en:

/home/deploy/consul/current/public/assets

Les agradecería cualquier ayuda que me puedan brindar.

Les comento que he realizado cambios al home y no he tenido problemas haciendo los cambios en

/home/deploy/consul/current/app/views/custom y creando las carpetas y directorios que corresponden.

**Comment by javierm** [comment]
Estimado @profesionalTI,

Junto con saludarte, y esperando te encuentres bien, quería preguntarte por la URL del repositorio donde estás haciendo esos cambios. En [tu repositorio de CONSUL](https://github.com/profesionalTI/consul/commits/master) no he encontrado los cambios que mencionas :thinking:.

**Comment by javierm** [comment]
Closing due to lack of reply.
