### ISSUE TITLE
Do I need this installer?

### ISSUE THREAD

**Issue by jfoclpf** [consul/installer#168]
I installed consul normally using manually installation 
https://decidelisboa.org/
Do I need this installer for anything else?

How do I put my consul in production mode?
Sorry, this is quite confusing for me

**Comment by javierm** [comment]
Hi, @jfoclpf :smile:.

The normal way to install CONSUL is using this installer. Manual installations are more prone to errors; depending your experience with Ruby on Rails, Nginx, Puma, PostgreSQL, Memcached, SSL, ... you might want to start from scratch using this installer. If you're confident the manual installation process has gone smoothly, you don't the installer.

Hope that helps!

**Comment by jfoclpf** [comment]
Thanks for your reply ;) my problem is that my server has already a lot of other important stuff running and I cannot risk to make an automatic installation wherein a lot of apt packages will be updated or installed automatically. 

But thanks again for the reply.

**Comment by jfoclpf** [comment]
and btw, I can deal well with nginx, passenger, ssh, nodejs, bash ;)
my problem is really ruby
