### ISSUE TITLE
 the remote end hung up unexpectedly

### ISSUE THREAD

**Issue by jagudo** [consul/installer#179]
Buenos días
Estamos intentando desplegar Consul en el Ayuntamiento de Badajoz y obtenemos un error que parece relacionado con el repositorio de GitHub.
Podéis ayudarnos? Gracias

TASK [folder_structure : Git clone CONSUL] *****************************************************************************
fatal: [192.168.1.146]: FAILED! => changed=true
  cmd: git clone --mirror https://github.com/consul/consul.git /home/deploy/consul/repo
  delta: '0:05:43.412387'
  end: '2021-05-19 10:44:39.135681'
  msg: non-zero return code
  rc: 128
  start: '2021-05-19 10:38:55.723294'
  stderr: |-
    Cloning into bare repository '/home/deploy/consul/repo'...
    error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
    fatal: the remote end hung up unexpectedly
    fatal: early EOF
    fatal: index-pack failed
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

**Comment by jagudo** [comment]
He probado a lanzar autónomamente el comando de clonado del repositorio y obtengo el mismo fallo:

~/consul# git clone --mirror https://github.com/consul/consul.git /home/deploy/consul/repo
Cloning into bare repository '/home/deploy/consul/repo'...
remote: Enumerating objects: 415316, done.
remote: Counting objects: 100% (2362/2362), done.
remote: Compressing objects: 100% (692/692), done.
error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by jagudo** [comment]
Buenas tardes, Javier

He ejecutado varias veces el instalador (alguna de ellas previo borrado de la carpeta /home/deploy) y sigue saliendo el mismo fallo.
Probé con una Debian 10 y, como salía este error, estoy probando ahora con un Ubuntu 20
Lo estoy lanzando todo en el mismo servidor, no conecto desde mi cliente windows; pero no creo q ese sea el motivo del error pq, lanzo aisladamente el git clone y falla también.
Tenemos un Fortigate de firewall en la red pero otras máquinas clonan de git sin problemas (esta misma mañana he instalado Geonode en otro servidor)

Gracias

**Comment by javierm** [comment]
He borrado algunas ramas de prueba que tenían ficheros un poco grandes por si reducir el tamaño del repositorio influye, aunque realmente no creo que esté relacionado.

Otra posible solución podría ser ejecutar esto en el servidor con el usuario "deploy":

```
git config --global http.postBuffer 1048576000
```

Si no funciona, un par de preguntas más: ¿desde esa máquina puedes clonar otros repositorios? ¿Y desde otras máquinas puedes clonar el repositorio de CONSUL?

**Comment by javierm** [comment]
Estupendo :smile:.
