### ISSUE TITLE
Adding Certbot ppa fails for Ubuntu 20.04

### ISSUE THREAD

**Issue by catileptic** [consul/installer#183]
For Ubuntu 20.04, [adding the Cerbot ppa](https://github.com/consul/installer/blob/master/roles/letsencrypt/tasks/main.yml#L8) fails with `The repository 'http://ppa.launchpad.net/certbot/certbot/ubuntu focal Release' does not have a Release file`. 

A workaround is removing the step that adds the cerbot ppa and installing certbot directly as per [the installation instructions for Ubuntu 20.04](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-20-04). I have a modified version of the `letsencrypt` role in [my fork](https://github.com/catileptic/installer/blob/master/roles/letsencrypt/tasks/main.yml). 

I'm not familiar with Ansible so I would not know how to write this in such a way that it checks the distro and version, but that _could_ be a way to solve the issue in the main Consul installer as well.

**Comment by javierm** [comment]
Hi, @catileptic :smile:.

Thanks for reporting! I've just opened #184 so the issue can be reproduced in our CI. We'll work on fixing it as soon as possible.

**Comment by javierm** [comment]
@catileptic Should be fixed now.  Thanks!
