### ISSUE TITLE
Capistrano deployment

### ISSUE THREAD

**Issue by DemocraciaPopular** [consul/installer#205]
Hi guys. I was finally able to get to the point to be able to deploy with Capistrano. However, I have a question.

The instructions in the installer docs for local development allow the user/developer to run latest Consul master branch. 

On the other hand, the instructions guide to deploy Capistrano guide the user to deploy a production instance of Consul from stable (1.5.0) branch. 

I my case, the stable branch works on remote server ~~but not on local environment~~. On the other hand, deploying master branch on local and remote works fine. 

~~So my question is, is this workflow intended mostly to work with latest master branch and leave stable production install untouched? That would make sense as deploying a stable version through capistrano wouldn't make sense if the stable version doesn't work locally (it would require to manually modify files on the vps, defeating the purpose of capistrano).~~

Anyway, I would appreciate some further elaboration on this workflow.

kind regards

ps: in the instructions, it instructs the user to run ```git checkout origin/1.5.0 -b stable``` but for me only works removing the "origin" word from the commmand.

**Comment by DemocraciaPopular** [comment]
An update: for some reason yesterday stable release didn't work on local environment but todays it works. 

Anyway, the question still stands. Is it better to have a stable release working on production, or the latest master version?
What is more convenient in terms of, say, upgrade to next release?

**Comment by javierm** [comment]
Hi, @DemocraciaPopular :smile:.

It's better to have a stable release on production because we don't guarantee that the `master` branch is production-ready at all times. We also provide instructions to upgrade from one release to the next one (usually it's just running the `consul:execute_release_tasks` task), but upgrading from a non-stable version is not officially supported.

Hope that clarifies the point!

**Comment by javierm** [comment]
Hi, @DemocraciaPopular :smile:.

I'm closing this issue as it was already answered. By all means, if you think this issue should still be open, please reopen it and tell us what we can do to solve it.
