### ISSUE TITLE
Staging environment

### ISSUE THREAD

**Issue by voodoorai2000** [consul/installer#23]
What
===
Add an option to run the playbook for a staging environment

Why
===
To be able to deploy changes to a staging environment using `cap staging/preproduction deploy` before deploying the changes to a production server

How
===
Add a variable `environment` and substitute the hardcoded `production` words and files in the installer

Notes
===
The current CONSUL codebase uses `preproduction` instead of `staging` environment
It's probably simpler to go ahead and use `preproduction` for now 👌

**Comment by javierm** [comment]
Closed by #98.
