### ISSUE TITLE
Capistrano Taks Fails

### ISSUE THREAD

**Issue by jesuxgslp** [consul/installer#36]
Scenario, libs and versions : 

Local Machine:
Ubuntu 16.04.4 LTS
ruby 2.3
usuario local: user
simplejson 3.8.1
ansible 2.5.4

Remote server:
Ubuntu 16.04.4 LTS
ruby 2.3
user: deploy (created by ansible )
python-simplejson 3.8.1
Ubuntu 16.04 x64

TASK [capistrano : Copy deploy.rb (locally)] ***************************************************************************************************************************************************************
fatal: [10.99.52.80]: FAILED! => {"changed": false, "checksum": "df14b6d8a11dd21c701813c32e1da2b6548c5e69", "dest": "/home/user/projects/installer/consul/config/deploy.rb", "gid": 1000, "group": "user", "mode": "0644", "msg": "chgrp failed: failed to look up group wheel", "owner": "deploy", "path": "/home/user/projects/installer/consul/config/deploy.rb", "size": 1922, "state": "file", "uid": 1001}
	to retry, use: --limit @/home/user/projects/installer/consul.retry

PLAY RECAP *************************************************************************************************************************************************************************************************
10.99.52.80                : ok=47   changed=3    unreachable=0    failed=1

**Comment by jesuxgslp** [comment]
Your are right, workaround:
Create  wheel group

`sudo addgroup wheel`

add you local user to wheel group

`sudo usermod -aG wheel user`

**Comment by allthesignals** [comment]
Sorry, I am also running into this issue. I am running (locally) from a Mac, which is probably the source of the issue. I have completed the Mac equivalent of @jesuxgslp's instructions with no luck (more precisely, the error I'm seeing is from #37). 

When I hardcode the lines `owner: deploy` for "local" connections _with my local username_, I get further along. But this seems very wrong. Any thoughts? Mac's user group creation CLI is a [bit wild](https://superuser.com/questions/1154564/how-to-create-a-user-from-the-macos-command-line).

**Comment by voodoorai2000** [comment]
Hey @allthesignals, 

Yes... the capistrano feature in the installer is giving quite a few problems 🤔
Maybe we should just remove it from the initial installation step and deal with deploys separately.

Let me give it a try, see how it would look 😊

**Comment by allthesignals** [comment]
Thank you, @voodoorai2000 - I went ahead and forked with my changes, but I'm not sure how you feel about them: https://github.com/allthesignals/installer/blob/master/roles/capistrano/tasks/main.yml#L24. 

Let me know if you'd like me to PR something.

**Comment by voodoorai2000** [comment]
Hey @allthesignals,

Sure, that should work too 😌
It all seems to stem from user permission configurations. I'm only worried that there will be other user permission issues 🤔

Hopefully once we have separated the initial installation from deployment with Capistrano, things will be smother, as we'll clone using our local_owner user from the beginning, and life will be beautiful 😊

In the meantime, [here](https://github.com/consul/installer/compare/no-capistrano?expand=1) is a branch with the simplified setup, without Capistrano. I'll try to clean it up this week and hopefully things will run smoother. Feel free to try it out!

Help with PRs is very welcomed! 🎉
However changing those user permissions will probably become obsolete very soon, don't want to make you work in vain... But if you have time to check out other issues, it be awesome!

**Comment by voodoorai2000** [comment]
Alright @allthesignals, we have merged a few PRs that should help in the initial setup
Let me know how it works for you!

Cheers!

[1] https://github.com/consul/installer/pull/43
https://github.com/consul/installer/pull/44
https://github.com/consul/installer/pull/45
https://github.com/consul/installer/pull/46

**Comment by allthesignals** [comment]
@voodoorai2000 wanted to thank you and also let you know this new version you published works fine on a fresh digital ocean droplet. Thanks :)

**Comment by voodoorai2000** [comment]
Glad to hear!!! 🎉
