### ISSUE TITLE
Capistrano: "database.yml does not exist"

### ISSUE THREAD

**Issue by allthesignals** [consul/installer#50]
Trying out the new capistrano installer. Again, thank you for continuing to improve this awesome installer.

I'm seeing this:
```
00:02 deploy:check:linked_files
      ERROR linked file /var/www/consul/shared/config/database.yml does not exist
```

I don't know enough about the use of the shared folder. Did I miss a step? Thanks!

**Comment by allthesignals** [comment]
RTFM

**Comment by voodoorai2000** [comment]
@allthesignals 😄Yes, the deploy path should be `/home/deploy/consul/`

We'll fix that in CONSUL's repo to make it the default 👍 
Thanks for pointing it out! ❤️

**Comment by allthesignals** [comment]
Ha, thanks @voodoorai2000 - I self-closed because I didn't read the instructions closely enough :)
