### ISSUE TITLE
Capistrano RVM task looks in root

### ISSUE THREAD

**Issue by allthesignals** [consul/installer#51]
Hello, not sure if I've configured the installer incorrectly, but Capistrano seems to be checking the `/root/` directory for rvm: 

```
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as root@dev.pbnyc.participatorybudgeting.org: bundle exit status: 102
bundle stdout: Can not find rvm in '/root/.rvm'.
bundle stderr: Nothing written
```

I think this is in the deploy user's:

`/home/deploy/.rvm`

Any ideas?

**Comment by allthesignals** [comment]
If I symlink /home/deploy/.rvm with /root/.rvm, it works fine... is there a way I can tell the `bundle:install` step to use a specific rvm? Or perhaps my deploy user should just be `deploy`? (In the latter case, I run into permissions errors, which seem weird. For example, `deploy` can't `scp` some special rvm-auto.sh file).

**Comment by voodoorai2000** [comment]
Hey @allthesignals 😊

Yes, we need to fix this one 😌

I thought it wasn't critical as RVM should have installed Ruby already, in a previous step of the Installer. So, I commented it out in the capistrano branch[1], temporarily, until we figure it out 😌

¿Does `cap production deploy` work smoothly if comment that line?

[1] https://github.com/consul/consul/compare/capistrano?expand=1#diff-6dc906be0643182e5bae6aa1506221e6R44
