### ISSUE TITLE
Task Update rvm returs fatal

### ISSUE THREAD

**Issue by kevieman** [consul/installer#52]
Hello, Im trying to deploy Consul on a vps.
While trying to run the playbook I get the following Error at the update rvm task:

```
TASK [galaxy/rvm_io.ruby : Update rvm] *****************************************
fatal: [149.210.191.114]: FAILED! => {"changed": false, "cmd": "/home/deploy/.rvm/bin/rvm get stable && /home/deploy/.rvm/bin/rvm reload", "delta": "0:00:00.233758", "end": "2018-10-16 13:08:11.563976", "msg": "non-zero return code", "rc": 1, "start": "2018-10-16 13:08:11.330218", "stderr": "Archives path '/usr/share/rvm/archives' not writable, aborting.", "stderr_lines": ["Archives path '/usr/share/rvm/archives' not writable, aborting."], "stdout": "", "stdout_lines": []}
```
My local machine runs **Ubuntu 18.04.1 LTS**
And my remote server runs: **Ubuntu 16.04.5 LTS**

I do not have direct Acces to the root of the remote server but I have Acces to an user with the same rights. So I adjusted the host file and the playbook to look like this:

Host:
```
[servers]
xxx.xxx.xxx.xxx ansible_ssh_extra_args='-o StrictHostKeyChecking=no' ansible_ssh_private_key_file='~/.ssh/id_rsa' ansible_port=22 ansible_ssh_user='consuladmin'
```
Playbook:
```
---

- hosts: all
  remote_user: consuladmin
  become: yes
  vars_files:
    - ./vars.yml
  roles:
    - postgresql
```
Any help?

**Comment by kevieman** [comment]
It was probably something i did before. I solved it by completely removing  rvm from my remote host. And then run the playbook again.

**Comment by voodoorai2000** [comment]
Fantastic @kevieman, glad to hear 😌
Thanks for giving a hand @JordyKingz 🙌
