### ISSUE TITLE
500 | Internal server error on /valuation page

### ISSUE THREAD

**Issue by kevieman** [consul/installer#54]
After deployment when I try tot access the valuation page in the admin panel I get a 500 internal server error.

**Edit:** This only happens when there are no participatory budget present.

**Comment by sturpin** [comment]
As soon as you create a participatory budget, it will be solved :)

**Comment by sturpin** [comment]
> 
> 
> After deployment when I try tot access the valuation page in the admin panel I get a 500 internal server error.

As soon as you create a participatory budget, it will be solved :)

**Comment by kevieman** [comment]
It did indeed. After I created an participatory budget and made it public i could Acces the valuation page. Issue still remains if there are no budgets.
