### ISSUE TITLE
Add Unicorn init script

### ISSUE THREAD

**Issue by pablovg2** [consul/installer#56]
With the clean install there is not a unicorn init script, I think it is necessary for start Consul after reboot or to restart it easy.

## How

This is an standar file to create a unicorn init script that could be used to make a template for Ansible and a task to deploy it.

```#!/bin/sh

### BEGIN INIT INFO
# Provides:          unicorn
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the unicorn app server
# Description:       starts unicorn using start-stop-daemon
### END INIT INFO

set -e

USAGE="Usage: $0 <start|stop|restart|upgrade|rotate|force-stop>"

# app settings
USER="deploy"
APP_NAME="appname"
APP_ROOT="/home/$USER/$APP_NAME"
ENV="production"

# environment settings
PATH="/home/$USER/.rbenv/shims:/home/$USER/.rbenv/bin:$PATH"
CMD="cd $APP_ROOT && bundle exec unicorn -c config/unicorn.rb -E $ENV -D"
PID="$APP_ROOT/shared/pids/unicorn.pid"
OLD_PID="$PID.oldbin"

# make sure the app exists
cd $APP_ROOT || exit 1

sig () {
  test -s "$PID" && kill -$1 `cat $PID`
}

oldsig () {
  test -s $OLD_PID && kill -$1 `cat $OLD_PID`
}

case $1 in
  start)
    sig 0 && echo >&2 "Already running" && exit 0
    echo "Starting $APP_NAME"
    su - $USER -c "$CMD"
    ;;
  stop)
    echo "Stopping $APP_NAME"
    sig QUIT && exit 0
    echo >&2 "Not running"
    ;;
  force-stop)
    echo "Force stopping $APP_NAME"
    sig TERM && exit 0
    echo >&2 "Not running"
    ;;
  restart|reload|upgrade)
    sig USR2 && echo "reloaded $APP_NAME" && exit 0
    echo >&2 "Couldn't reload, starting '$CMD' instead"
    $CMD
    ;;
  rotate)
    sig USR1 && echo rotated logs OK && exit 0
    echo >&2 "Couldn't rotate logs" && exit 1
    ;;
  *)
    echo >&2 $USAGE
    exit 1
    ;;
esac```

**Comment by pabloacastillo** [comment]
Please, i had to restart the server and all i get is a 502.
This is a need.

**Comment by voodoorai2000** [comment]
Hey @pabloacastillo!

Yes, sorry about that, we need to add some documentation/scripts to start unicorn after a server reboot 🙏

Have you followed the [capistrano configuration](https://github.com/consul/installer#deploys-with-capistrano)? In that case try a `cap production deploy`

Otherwise you can start the server manually with [this command](https://github.com/consul/installer/blob/master/roles/unicorn/tasks/main.yml#L37):

**Comment by gildvir** [comment]
> Hey @pabloacastillo!
> 
> Yes, sorry about that, we need to add some documentation/scripts to start unicorn after a server reboot pray
> 
> Have you followed the [capistrano configuration](https://github.com/consul/installer#deploys-with-capistrano)? In that case try a `cap production deploy:restart`
> 
> Otherwise you can start the server manually with [this command](https://github.com/consul/installer/blob/master/roles/unicorn/tasks/main.yml#L37).
on the capistrano configuration? link it says to uncomment the # - capistrano on the consul.yml but it's not there!
it is on the app.yml
am i right?

**Comment by voodoorai2000** [comment]
Hey @gildvir,
That's right 👍 Thanks for letting us know, documentation updated.
