### ISSUE TITLE
Playbook is stuck

### ISSUE THREAD

**Issue by kevieman** [consul/installer#57]
I used the method in issue #14 to install consul on my Ubuntu server. The first time i could run the playbook without any problem. Only when I try to run the playbook again it gets stuck on a certain task.
It gets stuck on:
```
TASK [rails : Load configuration seeds] **************************************************************************
task path: /root/installer/roles/rails/tasks/main.yml:65
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1542197596.54-5055084817189 `" && echo ansible-tmp-1542197596.54-5055084817189="` echo /root/.ansible/tmp/ansible-tmp-1542197596.54-5055084817189 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/commands/command.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-32731ATOFOF/tmpLysohr TO /root/.ansible/tmp/ansible-tmp-1542197596.54-5055084817189/AnsiballZ_command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1542197596.54-5055084817189/ /root/.ansible/tmp/ansible-tmp-1542197596.54-5055084817189/AnsiballZ_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1542197596.54-5055084817189/AnsiballZ_command.py && sleep 0'
```

**Comment by kevieman** [comment]
I found an temporary solution. But this is something I would like to avoid doing.

First I needed to delete the deploy user (and the /home/deploy directory) and the wheel group.
```
sudo deluser deploy
sudo rm -r /home/deploy
sudo delgroup wheel
```
After I deleted all the related Packages with the following command.
```
apt purge nginx-common nginx-core nodejs postgresql-9.6 postgresql-client-9.6 postgresql-client-common postgresql-contrib-9.6 rake ruby ruby-dev ruby-did-you-mean ruby-minitest ruby-net-telnet ruby-power-assert ruby-test-unit ruby2.3 ruby2.3-dev rubygems-integration
```
This resulted in an complete clean installation and I could rerun the playbook on the server. Just like I said I want to avoid doing this every time I want to run the playbook.

**Comment by voodoorai2000** [comment]
Hey @kevieman,

I just [updated the README](https://github.com/consul/installer/pull/58/files) with a system package update that seems to be necessary.

However I cannot reproduce this error. If you are still experiencing this problem could you try running the installer in a fresh server?

Cheers!

**Comment by kevieman** [comment]
Thank you @voodoorai2000,

I got past the "Load configuration seeds" task but now I am stuck on the "Start Unicorn" Task. I get the following error;

```
TASK [unicorn : Kill running process] ******************************************
changed: [127.0.0.1] => (item=24718)

TASK [unicorn : Start Unicorn] *************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "/home/deploy/.rvm/gems/ruby-2.3.2/wrappers/unicorn -c config/unicorn.rb -E production -D", "delta": "0:00:01.262636", "end": "2018-11-21 14:07:30.682360", "msg": "non-zero return code", "rc": 1, "start": "2018-11-21 14:07:29.419724", "stderr": "master failed to start, check stderr log for details", "stderr_lines": ["master failed to start, check stderr log for details"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/root/installer/consul.retry
```
** This only hapens when I try to run the playbook twice or more times. The first time I run the playbook it works perfectly fine.

**Comment by voodoorai2000** [comment]
Aaaah very interesting, that sounds like  an issue wit the immutability of the installer. I cannot reproduce it with the standard configuration in the master branch. But it could have to do with the Capistrano configuration 🤔We'll review it and fix it 😌

A temporary solution is always to rebuild the server with a fresh distribution and rerun the installer 🙏

**Comment by kevieman** [comment]
So I think this issue is solved so i'm closing it. However i Will make a new issue regarding the Unicorn error. This is because the situation has changed.
