### ISSUE TITLE
Add documentation on how to setup without root access

### ISSUE THREAD

**Issue by voodoorai2000** [consul/installer#62]
Context
===
The installer assumes we can login as the `root` user using a public ssh key and without password.  Which is only used to create a `deploy` user, who is the one that will actually install all libraries. 

However some developers are not granted `root` user access and cannot run the installer with the default configuration.

Objectives
===
Allow the installer to be run with any user with sudo privileges.

How
===
After doing a couple of tests, it seems we only need to add this line: `remote_user: name_of_user` [here](https://github.com/consul/installer/blob/master/consul.yml#L4).

**Comment by afeld** [comment]
I'd suggest users do this in their [inventory](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html), using `ansible_user=<name_of_user>`. Bonus that the code doesn't have to be modified.

**Comment by afeld** [comment]
> Allow the installer to be run with any user with sudo privileges.

This already worked for me...

**Comment by javierm** [comment]
Closed via #91.
