### ISSUE TITLE
Consolidate documentation

### ISSUE THREAD

**Issue by afeld** [consul/installer#74]
Right now, most of the documentation for production setup is in the README of this repository, while a bit lives in [the documentation site](https://consul_docs.gitbooks.io/docs/content/en/getting_started/servers.html). I suggest deciding on one place (for now - can change later), or at least linking between them.

**Comment by afeld** [comment]
cc https://github.com/consul/docs/issues/29

**Comment by voodoorai2000** [comment]
Thanks @afeld!

Closed via https://github.com/consul/docs/pull/65
