### ISSUE TITLE
Restarting the Server leaves the application dead

### ISSUE THREAD

**Issue by xrkolovos** [consul/installer#94]
We followed your install steps and magically the app runned. We restarted the server and the app was not running. This steps is supposed to be for production environments. Restarting the server shouldn't leave the application killed. Is there a way to keep a service running the app alive?

The install scripts does so many hidden jobs, the person that deploys the app is hard to understand. It might be easy for ruby people to understand it, but for me that i am a 10 years none ruby developer seems complicated. It used to be more clear what you should do to install for example a wordpress site. I don't know if ruby makes the things more complicate, but i would expect to grab some files, configure the db, configure ngnix/ruby and Boom the website appears. 

We didn't also find any mention in the documentations for the update procedure. Does it exist?

thank you in advance for clarifying our questions.

**Comment by voodoorai2000** [comment]
Hey @xrkolovos!

Thank you so much for letting us know about this! 👌

Indeed, we need to add the commands to start unicorn after a reboot. We've been trying out some places to add it and we got it working. We'll send a PR very soon. 🙏 

For now, please check out the section on how to configure [deploys with Capistrano](https://github.com/consul/installer#deploys-with-capistrano). With that you should be able to restart the application running a `cap production deploy:restart`

Regarding updates: Apart from the basic [difference between the roles of the Ansible and Capistrano](https://github.com/consul/installer/issues/82), the Installer's script should be idempotent, meaning you should be able to run the installer multiples times and get the same result. This can be tricky depending on what has changed in the Installer's code. We do keep it in mind though, and hopefully just my rerunning the installer you should be able to have the latest features configured in your server, without modifying the production database.
